### ISSUE TITLE
bug(icon): nf-mdi-corn has been removed

### ISSUE THREAD

**Issue by CAESIUS-TIM** [hafiz-muhammad/neofetch-config#1]
![image](https://github.com/hafiz-muhammad/neofetch-config/assets/60285058/4e7a63af-a32b-46e6-bffb-2bfa7d83aaac)

https://github.com/hafiz-muhammad/neofetch-config/blob/62ba7fe177045306a46780ca62005cd7f225af29/config.conf#L8

**Comment by hafiz-muhammad** [comment]
Thank you for raising this issue. Icons have been updated.
